environment:
  global:
    TOXENV: py

  matrix:
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python34-x64
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -U tox

build: false

test_script:
  - python -m tox

branches:
  only:
    - master

cache:
  - '%LOCALAPPDATA%\pip\Cache'
